# Document: http://goreleaser.com
# This config is for normal release. See .goreleaser-nightly.yml for nightly release.
before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/codebase/
    ldflags: -s -w -X github.com/khulnasoft/codebase/commands.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - id: main
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    files:
      - LICENSE
      - README.md

brews:
  - repository:
      owner: codebase
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/khulnasoft/codebase
    description: Automated code review tool integrated with any code analysis tools regardless of programming language.
    test: |
      system "#{bin}/codebase -version"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"