version: 2

jobs:
  lint:
    working_directory: ~/codebase
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: System information
          command: 'echo "Golang $(go version)"'
      - run: 'curl -sfL https://raw.githubusercontent.com/khulnasoft/codebase/master/install.sh| sh -s -- -b $(go env GOPATH)/bin'
      - run: go install golang.org/x/lint/golint@latest
      - run:
          command: |-
            set +o pipefail
            golint ./... | codebase -f=golint -name=golint-circleci -reporter=github-pr-reviewe
workflows:
  version: 2
  lint:
    jobs:
      - lint
